// Package migrate provides Gas Town → Gas City migration logic.
//
// It reads a Gas Town's JSON configuration (town.json, settings/config.json,
// rigs.json) and generates a Gas City city.toml that references the gastown
// topology remotely via a named [topologies.gastown] section.
package migrate

import (
	"fmt"
	"sort"
	"strings"

	"github.com/steveyegge/gastown/internal/beads"
	"github.com/steveyegge/gastown/internal/config"
	"github.com/steveyegge/gastown/internal/constants"
)

// TownSnapshot aggregates all town config needed for migration.
type TownSnapshot struct {
	Name         string                           // from town.json
	DefaultAgent string                           // from settings/config.json
	Agents       map[string]*config.RuntimeConfig // custom agents
	RoleAgents   map[string]string                // role→agent mapping
	Rigs         map[string]config.RigEntry       // from rigs.json
}

// ReadTownSnapshot loads all config from a town root directory.
func ReadTownSnapshot(townRoot string) (*TownSnapshot, error) {
	// Verify this is actually a town root.
	found := beads.FindTownRoot(townRoot)
	if found == "" || found != townRoot {
		return nil, fmt.Errorf("not a Gas Town root: %s (no mayor/town.json found)", townRoot)
	}

	// Load town identity.
	townPath := constants.MayorTownPath(townRoot)
	townCfg, err := config.LoadTownConfig(townPath)
	if err != nil {
		return nil, fmt.Errorf("loading town config: %w", err)
	}

	// Load town settings (creates defaults if missing).
	settingsPath := config.TownSettingsPath(townRoot)
	settings, err := config.LoadOrCreateTownSettings(settingsPath)
	if err != nil {
		return nil, fmt.Errorf("loading town settings: %w", err)
	}

	// Load rigs registry.
	rigsPath := constants.MayorRigsPath(townRoot)
	rigsCfg, err := config.LoadRigsConfig(rigsPath)
	if err != nil {
		// Rigs file is optional — a town with no rigs is valid.
		rigsCfg = &config.RigsConfig{Rigs: map[string]config.RigEntry{}}
	}

	snap := &TownSnapshot{
		Name:         townCfg.Name,
		DefaultAgent: settings.DefaultAgent,
		Agents:       settings.Agents,
		RoleAgents:   settings.RoleAgents,
		Rigs:         rigsCfg.Rigs,
	}

	// Normalize nils to empty maps.
	if snap.Agents == nil {
		snap.Agents = map[string]*config.RuntimeConfig{}
	}
	if snap.RoleAgents == nil {
		snap.RoleAgents = map[string]string{}
	}
	if snap.Rigs == nil {
		snap.Rigs = map[string]config.RigEntry{}
	}

	return snap, nil
}

// GenerateCityTOML builds a city.toml string from a TownSnapshot.
func GenerateCityTOML(snap *TownSnapshot) (string, error) {
	if snap.Name == "" {
		return "", fmt.Errorf("town name is required")
	}

	provider := snap.DefaultAgent
	if provider == "" {
		provider = "claude"
	}

	var b strings.Builder

	// Header and workspace.
	fmt.Fprintf(&b, "# Generated by gt migrate from town %q\n\n", snap.Name)
	fmt.Fprintf(&b, "[workspace]\n")
	fmt.Fprintf(&b, "name = %q\n", snap.Name)
	fmt.Fprintf(&b, "provider = %q\n", provider)
	fmt.Fprintf(&b, "topology = \"gastown\"\n")

	// Named topology reference.
	fmt.Fprintf(&b, "\n[topologies.gastown]\n")
	fmt.Fprintf(&b, "source = \"https://github.com/steveyegge/gascity.git\"\n")
	fmt.Fprintf(&b, "ref = \"main\"\n")
	fmt.Fprintf(&b, "path = \"examples/gastown/topologies/gastown\"\n")

	// Provider sections from custom agents.
	agentNames := sortedKeys(snap.Agents)
	for _, name := range agentNames {
		rc := snap.Agents[name]
		if rc == nil {
			continue
		}
		fmt.Fprintf(&b, "\n[providers.%s]\n", name)
		cmd := rc.Command
		if cmd == "" {
			cmd = "claude"
		}
		fmt.Fprintf(&b, "command = %q\n", cmd)
		if len(rc.Args) > 0 {
			fmt.Fprintf(&b, "args = [%s]\n", tomlStringArray(rc.Args))
		}
		if len(rc.Env) > 0 {
			envKeys := make([]string, 0, len(rc.Env))
			for k := range rc.Env {
				envKeys = append(envKeys, k)
			}
			sort.Strings(envKeys)
			for _, k := range envKeys {
				fmt.Fprintf(&b, "%s = %q\n", k, rc.Env[k])
			}
		}
		if rc.PromptMode != "" {
			fmt.Fprintf(&b, "prompt_mode = %q\n", rc.PromptMode)
		}
		if rc.Tmux != nil {
			if len(rc.Tmux.ProcessNames) > 0 {
				fmt.Fprintf(&b, "process_names = [%s]\n", tomlStringArray(rc.Tmux.ProcessNames))
			}
			if rc.Tmux.ReadyDelayMs > 0 {
				fmt.Fprintf(&b, "ready_delay_ms = %d\n", rc.Tmux.ReadyDelayMs)
			}
			if rc.Tmux.ReadyPromptPrefix != "" {
				fmt.Fprintf(&b, "ready_prompt_prefix = %q\n", rc.Tmux.ReadyPromptPrefix)
			}
		}
	}

	// Daemon section.
	fmt.Fprintf(&b, "\n[daemon]\n")
	fmt.Fprintf(&b, "patrol_interval = \"30s\"\n")

	// Role agents as comments.
	if len(snap.RoleAgents) > 0 {
		roleNames := make([]string, 0, len(snap.RoleAgents))
		for role := range snap.RoleAgents {
			roleNames = append(roleNames, role)
		}
		sort.Strings(roleNames)
		fmt.Fprintf(&b, "\n# Role-agent mappings from Gas Town (topology handles these):\n")
		for _, role := range roleNames {
			fmt.Fprintf(&b, "# %s = %q\n", role, snap.RoleAgents[role])
		}
	}

	// Rig entries.
	rigNames := sortedRigKeys(snap.Rigs)
	for _, name := range rigNames {
		entry := snap.Rigs[name]
		fmt.Fprintf(&b, "\n[[rigs]]\n")
		fmt.Fprintf(&b, "name = %q\n", name)
		fmt.Fprintf(&b, "path = %q\n", entry.LocalRepo)
		fmt.Fprintf(&b, "topology = \"gastown\"\n")
		if entry.GitURL != "" {
			fmt.Fprintf(&b, "# git_url = %q\n", entry.GitURL)
		}
	}

	return b.String(), nil
}

// tomlStringArray formats a string slice as TOML inline array values.
func tomlStringArray(ss []string) string {
	quoted := make([]string, len(ss))
	for i, s := range ss {
		quoted[i] = fmt.Sprintf("%q", s)
	}
	return strings.Join(quoted, ", ")
}

// sortedKeys returns the sorted keys of a map[string]*config.RuntimeConfig.
func sortedKeys(m map[string]*config.RuntimeConfig) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// sortedRigKeys returns the sorted keys of a map[string]config.RigEntry.
func sortedRigKeys(m map[string]config.RigEntry) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
